<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class CustomerPOsManagement extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
              "project_id"             => "required",
              "customer_po_number"     => "required",
              "amount_without_tax"     => "required",
              "amount_with_tax"        => "required",
              "customer_po_issue_date" => "required|date",
              "customer_po_start_date" => "required|date",
              "customer_po_end_date"   => "required|date",
              "details_input"          => 'required',
        ];
    }

    public function messages()
    {
        return parent::messages(); // TODO: Change the autogenerated stub
    }
}
