<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class DamconAssetsManagementRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
              "asset_item_id"       => "required",
              "supplier_id"         => "required|numeric",
              "project_id"          => "required|numeric",
              "date_of_purchase"    => "required|date",
              "item_condition"      => "required",
              "mode_of_purchase"    => "required|numeric",
              "mode_of_payment"     => "required|numeric",
              "asset_brand"         => "required",
              "model"               => "required",
              "registration_number" => "required",
              "engine_name"         => "required",
              "chassis_number"      => "required",
              "color"               => "required",
              "engine_capacity"     => "required",
              "milage"              => "required",
              "asset_Location"      => "required",
              "purchase_price"      => "required",
//              "specifications_1"    => "required",
//              "specifications_2"    => "required",
//              "description_input"   => "required",
              "comments"            => "required",
        ];
    }

    public function messages()
    {
        return parent::messages(); // TODO: Change the autogenerated stub
    }
}
