<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class RentalItemsRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {

        return [
              "rental_id"             => "required|max:220",
              "rental_name"           => "required",
            //   "date_of_agreement"     => "required|date",
            //   "monthly_rental_amount" => "required",
            //   "item_condition"        => "required|max:50",
            //   "brand"                 => "required|max:50",
              "supplier_id"           => "required|numeric",
            //   "model"                 => "required|max:50",
            //   "engine_name"           => "required",
            //   "chassis_number"        => "required",
            //   "color"                 => "required",
            //   "engine_capacity"       => "required",
            //   "current_milage"        => "required",
            //   "current_localtion"     => "required",
            //   "specifications_1"      => "required",
            //   "description_input"     => "required",
            //   "comments"              => "required|max:500",
        ];
    }

    public function messages()
    {
        return parent::messages(); // TODO: Change the autogenerated stub
    }
}
