<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class RentalPORequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
              "purchase_od_number"         => 'required',
            //   "agreement_number"           => 'required',
              "type"                       => "required|numeric",
              "supplier_id"                => 'required|numeric',
              "project_id"                 => 'required|numeric',
            //   "issue_date"                 => 'required|date',
            //   "purchase_order_month"       => 'required',
            //   "region"                     => 'required|min:2|max:20',
              "tax_body_id"                => 'required|numeric',
              "taxation_month"             => 'required',
              "tax_body_percentage"        => 'required|numeric',
              "sales_tax_wh"               => 'required|numeric',
              "supplier_tax_deduction_1"   => 'required|numeric',
              "supplier_tax_deduction_2"   => 'required|numeric',
              "item_name.*"                => 'required',
              "item_quantity.*"            => 'required',
              "item_monthly_rent.*"        => 'required',
              "comments"                   => 'required|min:1',
        ];
    }

    public function messages()
    {
        return parent::messages(); // TODO: Change the autogenerated stub
    }
}
